# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/svpriyanka/OOP/MyRepo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/svpriyanka/OOP/MyRepo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/svpriyanka/OOP/MyRepo/CMakeFiles /home/svpriyanka/OOP/MyRepo/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/svpriyanka/OOP/MyRepo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named featureExtractor

# Build rule for target.
featureExtractor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 featureExtractor
.PHONY : featureExtractor

# fast build rule for target.
featureExtractor/fast:
	$(MAKE) -f CMakeFiles/featureExtractor.dir/build.make CMakeFiles/featureExtractor.dir/build
.PHONY : featureExtractor/fast

MainScript.o: MainScript.cpp.o
.PHONY : MainScript.o

# target to build an object file
MainScript.cpp.o:
	$(MAKE) -f CMakeFiles/featureExtractor.dir/build.make CMakeFiles/featureExtractor.dir/MainScript.cpp.o
.PHONY : MainScript.cpp.o

MainScript.i: MainScript.cpp.i
.PHONY : MainScript.i

# target to preprocess a source file
MainScript.cpp.i:
	$(MAKE) -f CMakeFiles/featureExtractor.dir/build.make CMakeFiles/featureExtractor.dir/MainScript.cpp.i
.PHONY : MainScript.cpp.i

MainScript.s: MainScript.cpp.s
.PHONY : MainScript.s

# target to generate assembly for a file
MainScript.cpp.s:
	$(MAKE) -f CMakeFiles/featureExtractor.dir/build.make CMakeFiles/featureExtractor.dir/MainScript.cpp.s
.PHONY : MainScript.cpp.s

src/FeatureExtractor.o: src/FeatureExtractor.cpp.o
.PHONY : src/FeatureExtractor.o

# target to build an object file
src/FeatureExtractor.cpp.o:
	$(MAKE) -f CMakeFiles/featureExtractor.dir/build.make CMakeFiles/featureExtractor.dir/src/FeatureExtractor.cpp.o
.PHONY : src/FeatureExtractor.cpp.o

src/FeatureExtractor.i: src/FeatureExtractor.cpp.i
.PHONY : src/FeatureExtractor.i

# target to preprocess a source file
src/FeatureExtractor.cpp.i:
	$(MAKE) -f CMakeFiles/featureExtractor.dir/build.make CMakeFiles/featureExtractor.dir/src/FeatureExtractor.cpp.i
.PHONY : src/FeatureExtractor.cpp.i

src/FeatureExtractor.s: src/FeatureExtractor.cpp.s
.PHONY : src/FeatureExtractor.s

# target to generate assembly for a file
src/FeatureExtractor.cpp.s:
	$(MAKE) -f CMakeFiles/featureExtractor.dir/build.make CMakeFiles/featureExtractor.dir/src/FeatureExtractor.cpp.s
.PHONY : src/FeatureExtractor.cpp.s

src/GaborFilter.o: src/GaborFilter.cpp.o
.PHONY : src/GaborFilter.o

# target to build an object file
src/GaborFilter.cpp.o:
	$(MAKE) -f CMakeFiles/featureExtractor.dir/build.make CMakeFiles/featureExtractor.dir/src/GaborFilter.cpp.o
.PHONY : src/GaborFilter.cpp.o

src/GaborFilter.i: src/GaborFilter.cpp.i
.PHONY : src/GaborFilter.i

# target to preprocess a source file
src/GaborFilter.cpp.i:
	$(MAKE) -f CMakeFiles/featureExtractor.dir/build.make CMakeFiles/featureExtractor.dir/src/GaborFilter.cpp.i
.PHONY : src/GaborFilter.cpp.i

src/GaborFilter.s: src/GaborFilter.cpp.s
.PHONY : src/GaborFilter.s

# target to generate assembly for a file
src/GaborFilter.cpp.s:
	$(MAKE) -f CMakeFiles/featureExtractor.dir/build.make CMakeFiles/featureExtractor.dir/src/GaborFilter.cpp.s
.PHONY : src/GaborFilter.cpp.s

src/GaborPhasePatterns.o: src/GaborPhasePatterns.cpp.o
.PHONY : src/GaborPhasePatterns.o

# target to build an object file
src/GaborPhasePatterns.cpp.o:
	$(MAKE) -f CMakeFiles/featureExtractor.dir/build.make CMakeFiles/featureExtractor.dir/src/GaborPhasePatterns.cpp.o
.PHONY : src/GaborPhasePatterns.cpp.o

src/GaborPhasePatterns.i: src/GaborPhasePatterns.cpp.i
.PHONY : src/GaborPhasePatterns.i

# target to preprocess a source file
src/GaborPhasePatterns.cpp.i:
	$(MAKE) -f CMakeFiles/featureExtractor.dir/build.make CMakeFiles/featureExtractor.dir/src/GaborPhasePatterns.cpp.i
.PHONY : src/GaborPhasePatterns.cpp.i

src/GaborPhasePatterns.s: src/GaborPhasePatterns.cpp.s
.PHONY : src/GaborPhasePatterns.s

# target to generate assembly for a file
src/GaborPhasePatterns.cpp.s:
	$(MAKE) -f CMakeFiles/featureExtractor.dir/build.make CMakeFiles/featureExtractor.dir/src/GaborPhasePatterns.cpp.s
.PHONY : src/GaborPhasePatterns.cpp.s

src/HGPP.o: src/HGPP.cpp.o
.PHONY : src/HGPP.o

# target to build an object file
src/HGPP.cpp.o:
	$(MAKE) -f CMakeFiles/featureExtractor.dir/build.make CMakeFiles/featureExtractor.dir/src/HGPP.cpp.o
.PHONY : src/HGPP.cpp.o

src/HGPP.i: src/HGPP.cpp.i
.PHONY : src/HGPP.i

# target to preprocess a source file
src/HGPP.cpp.i:
	$(MAKE) -f CMakeFiles/featureExtractor.dir/build.make CMakeFiles/featureExtractor.dir/src/HGPP.cpp.i
.PHONY : src/HGPP.cpp.i

src/HGPP.s: src/HGPP.cpp.s
.PHONY : src/HGPP.s

# target to generate assembly for a file
src/HGPP.cpp.s:
	$(MAKE) -f CMakeFiles/featureExtractor.dir/build.make CMakeFiles/featureExtractor.dir/src/HGPP.cpp.s
.PHONY : src/HGPP.cpp.s

src/SQI.o: src/SQI.cpp.o
.PHONY : src/SQI.o

# target to build an object file
src/SQI.cpp.o:
	$(MAKE) -f CMakeFiles/featureExtractor.dir/build.make CMakeFiles/featureExtractor.dir/src/SQI.cpp.o
.PHONY : src/SQI.cpp.o

src/SQI.i: src/SQI.cpp.i
.PHONY : src/SQI.i

# target to preprocess a source file
src/SQI.cpp.i:
	$(MAKE) -f CMakeFiles/featureExtractor.dir/build.make CMakeFiles/featureExtractor.dir/src/SQI.cpp.i
.PHONY : src/SQI.cpp.i

src/SQI.s: src/SQI.cpp.s
.PHONY : src/SQI.s

# target to generate assembly for a file
src/SQI.cpp.s:
	$(MAKE) -f CMakeFiles/featureExtractor.dir/build.make CMakeFiles/featureExtractor.dir/src/SQI.cpp.s
.PHONY : src/SQI.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... featureExtractor"
	@echo "... rebuild_cache"
	@echo "... MainScript.o"
	@echo "... MainScript.i"
	@echo "... MainScript.s"
	@echo "... src/FeatureExtractor.o"
	@echo "... src/FeatureExtractor.i"
	@echo "... src/FeatureExtractor.s"
	@echo "... src/GaborFilter.o"
	@echo "... src/GaborFilter.i"
	@echo "... src/GaborFilter.s"
	@echo "... src/GaborPhasePatterns.o"
	@echo "... src/GaborPhasePatterns.i"
	@echo "... src/GaborPhasePatterns.s"
	@echo "... src/HGPP.o"
	@echo "... src/HGPP.i"
	@echo "... src/HGPP.s"
	@echo "... src/SQI.o"
	@echo "... src/SQI.i"
	@echo "... src/SQI.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

